# Proton configuration with TLS enabled
logger:
  level: trace
  log: /var/log/proton-server/proton-server.log
  errorlog: /var/log/proton-server/proton-server.err.log
  size: 1000M
  count: 10
  console: 1

# Standard ports
http_port: 8123
tcp_port: 8463

# TLS ports
https_port: 8443
tcp_port_secure: 9440

# TLS/SSL configuration
openSSL:
  server:
    # Server certificate and key
    certificateFile: /etc/proton-server/certs/server.pem
    privateKeyFile: /etc/proton-server/certs/server-key.pem
    
    # CA certificate for client verification (mTLS)
    caConfig: /etc/proton-server/certs/ca.pem
    
    # DH parameters
    dhParamsFile: /etc/proton-server/certs/dhparam.pem
    
    # Verification mode - strict for mTLS
    verificationMode: strict
    
    # Protocol settings
    disableProtocols: 'sslv2,sslv3,tlsv1,tlsv1_1'
    preferServerCiphers: true
    cipherList: 'ECDHE+AESGCM:ECDHE+AES256:!aNULL:!MD5:!DSS'
    
    loadDefaultCAFile: false
  
  client:
    loadDefaultCAFile: false
    caConfig: /etc/proton-server/certs/ca.pem
    verificationMode: relaxed

listen_host: '::'

max_connections: 4096
keep_alive_timeout: 3
max_concurrent_queries: 100

uncompressed_cache_size: 8589934592
mark_cache_size: 5368709120

path: /var/lib/proton/
tmp_path: /var/lib/proton/tmp/
user_files_path: /var/lib/proton/user_files/
format_schema_path: /var/lib/proton/format_schemas/

users_config: users-tls.yaml
default_profile: default
default_database: default

timezone: UTC

builtin_dictionaries_reload_interval: 3600
max_session_timeout: 3600
default_session_timeout: 60

query_log:
  database: system
  table: query_log
  partition_by: toYYYYMM(event_date)
  flush_interval_milliseconds: 7500