name: Lint

on:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true
          allow-prerelease-opam: true

      - name: Install ocamlformat
        run: opam install ocamlformat

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v3

  lint-opam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true
          allow-prerelease-opam: true

      - name: Lint opam
        uses: ocaml/setup-ocaml/lint-opam@v3
        continue-on-error: true

  lint-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true
          allow-prerelease-opam: true

      - name: Lint doc
        uses: ocaml/setup-ocaml/lint-doc@v3

  lint-opam-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true
          allow-prerelease-opam: true

      - name: Install opam-dune-lint
        run: opam install opam-dune-lint -y

      - name: Check opam files are in sync with dune
        run: |
          opam exec -- opam-dune-lint
          if git diff --quiet -- proton.opam; then
            echo "✅ opam files are in sync with dune"
          else
            echo "❌ opam files are out of sync with dune. Please run 'opam exec -- opam-dune-lint' and commit the changes."
            git diff -- proton.opam
            exit 1
          fi
