name: Opam Dependency Submission

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: dependency-submission-${{ github.ref }}
  cancel-in-progress: true

jobs:
  opam-dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3
          dune-cache: true
          allow-prerelease-opam: true

      - name: Opam Dependency Submission
        uses: ocaml/setup-ocaml/analysis@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
